### PR TITLE
Fix/proxy/mode

### LINKED ISSUE #71: Plugin not working with Grafana => 6.7
Hi, 
The plugin needs some updating to work with Grafana version of 6.7  or higher as at the moment it does not work at all. 
The error message is "err.headers is not a function"

Thanks.

### PR DESCRIPTION
**Pull request by aurrelhebert**
fixes #71

### CODE REVIEW

**Review by miton18 — APPROVED** [review]

**Review by miton18 — APPROVED** [review]

**Comment by miton18** [comment]
We need to publish a new version in the registry ! ;-)
