### ISSUE TITLE
Plugin not working with Grafana => 6.7

### ISSUE THREAD

**Issue by simonc6372** [ovh/ovh-warp10-datasource#71]
Hi, 
The plugin needs some updating to work with Grafana version of 6.7  or higher as at the moment it does not work at all. 
The error message is "err.headers is not a function"

Thanks.

**Comment by ghost** [comment]
Hi, to be more specific, this is the Query Inspector that generates the message "err.headers is not a function" when there is an error during the execution of a query instead of displaying the Warpscript error message.

Bottom line: debugging a Warpscript query in grafana 7.0 is made almost impossible without the correct feedback.

**Comment by aurrelhebert** [comment]
Hello @simonc6372, 
To fix this behavior, I am now forcing a content-type in Warp10 queries. In addition with setting the parameter `x_content_type_options` to false in the Grafana setting, the Warp10 data source will be now working fine with the Grafana 7 version.
Thanks for this issue.
